export const data = [
  {
    id: 1,
    name: "seba",
    lastName: "Lescano",
    status: true,
    workStatus: true,
  },
  {
    id: 2,
    name: "seba",
    lastName: "Lescano",
    status: false,
    workStatus: true,
  },
  {
    id: 3,
    name: "seba",
    lastName: "Lescano",
    status: true,
    workStatus: false,
  },
  {
    id: 4,
    name: "seba",
    lastName: "Lescano",
    status: false,
    workStatus: false,
  },
  {
    id: 5,
    name: "seba",
    lastName: "Lescano",
    status: true,
    workStatus: true,
  },
  {
    id: 6,
    name: "seba",
    lastName: "Lescano",
    status: true,
    workStatus: true,
  },
  {
    id: 7,
    name: "seba",
    lastName: "Lescano",
    status: false,
    workStatus: true,
  },
  {
    id: 8,
    name: "seba",
    lastName: "Lescano",
    status: true,
    workStatus: false,
  },
  {
    id: 9,
    name: "seba",
    lastName: "Lescano",
    status: true,
    workStatus: false,
  },
  {
    id: 10,
    name: "seba",
    lastName: "Lescano",
    status: true,
    workStatus: true,
  },
];
